### ISSUE TITLE
TypeError: concat() got an unexpected keyword argument 'join_axes'

### ISSUE THREAD

**Issue by aam1r** [chungchiehlun/portfolio#1]
Thanks for posting this publicly, @chungchiehlun.

I am getting an error running this locally on Python 3.7:

```
Traceback (most recent call last):
  File "/Users/personal/Downloads/portfolio-master/backtesting.py", line 11, in <module>
    end_date = pd.Timestamp.today().normalize()
  File "/Users/personal/Downloads/portfolio-master/portfolio.py", line 67, in get_prices
    join_axes=[df.index]
TypeError: concat() got an unexpected keyword argument 'join_axes'
```

Can you post your requirements.txt? I am just using the latest versions for all packages and I think there may be a version mismatch.

**Comment by chungchiehlun** [comment]
I didn't have `requirements.txt` in this project. However, I ran this in Python 3.8.

**Comment by cy1690** [comment]
Hi guys,

<module>
    from dotenv import load_dotenv, find_dotenv

ModuleNotFoundError: No module named 'dotenv'

anyone have this message?

**Comment by chungchiehlun** [comment]
@cy1690
Your question did not related to the issue. Please open another one.
